version: "3"
services: 
    elasticsearch:
        image: elasticsearch:latest
        volumes:
            - elastic-data:/usr/share/elasticsearch/data

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db

    kibana:
        restart: always
        image: kibana:latest
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports: 
            - 5601:5601

    super-api:
        image: node:latest
        command: /bin/bash -c "./node_modules/.bin/nodemon --delay 2 --watch dist --inspect=0.0.0.0:9229 ./dist/server.js | ./node_modules/.bin/bunyan --color"
        working_dir: /app
        depends_on:
            - mongodb
            - elasticsearch
        ports:
            - 3636:3636
            - 9229:9229
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - LOG_LEVEL=trace
            - API_URL=http://localhost
            - API_PORT=3636

            - ROOT_PASSWD=root
            - JWT_SECRET=jwt_super_secret

            - MONGO_URL=mongodb://mongodb:27017/masuperdb
            - ELASTIC_URL=elasticsearch:9200

    super-api-test:
        image: node:latest
        command: /bin/bash -c "set -o pipefail && ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --colors --no-timeouts ./dist/tests/tests.js | ./node_modules/.bin/bunyan --color"
        working_dir: /app
        depends_on:
            - mongodb
            - elasticsearch
        volumes:
            - .:/app
        environment:
            - NODE_ENV=test
            - LOG_LEVEL=debug
            - API_URL=http://localhost
            - API_PORT=3637

            - ROOT_PASSWD=root
            - JWT_SECRET=jwt_super_secret

            - MONGO_URL=mongodb://mongodb:27017/masuperdb
            - ELASTIC_URL=elasticsearch:9200

volumes:
    mongo-data:
    elastic-data:
